spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}/${DB_NAME}?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope: profile, email
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope: user, email


app:
  auth:
    tokenSecret: ce069e2aba44d4507282e2812fbb5725ad4fe4c85bf308573a2c4b1fcf033778
    tokenExpirationMsec: 86400000


logging:
  level:
    org:
      springframework:
        security: TRACE
      hibernate:
        type: TRACE

iexapi:
  token: ${IEXAPI_TOKEN}

threads:
  number: 30


scheduler:
  threads:
    numer: 5